"use client"
import { FormEvent, useCallback, useEffect, useState } from "react"
import { AlertTriangle, CheckCircle2, Loader2, RefreshCw, Search, ShieldCheck, Trash2 } from "lucide-react"
import { BackButton } from "@/components/back-button"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { config } from "@/lib/config"
import { useOwnerUid } from "@/lib/use-owner-uid"
import { useI18n } from "@/lib/i18n/provider"
import { translateUpperOperationsText } from "@/components/upper-operations-arabic-layer"

type Review = { paymentId:string; verdict:"Final"|"Recovering"|"Manual Review"|"Conflict"|"Unknown"; reason:string; asOf:string; createdAt?:string; updatedAt?:string; parties:Record<string,unknown>; canonical:Record<string,unknown>; database:Record<string,unknown>; refund:Record<string,unknown>; action:{allowed:false;canPruneFromQueue?:boolean;message:string} }
type Queue = { available:true; asOf:string; items:Review[]; counts:{total:number;recovering:number;manualReview:number;conflicts:number;unknown:number;refunds:number}; note?:string|null }
const badge=(v:Review["verdict"])=>v==="Final"?"bg-green-600":v==="Recovering"?"bg-blue-600":v==="Conflict"?"bg-red-600":"bg-amber-600"
export default function EmergencyPage(){
 const {locale}=useI18n(); const tr=(value:string)=>translateUpperOperationsText(locale,value);
 const {uidData}=useOwnerUid(); const [mounted,setMounted]=useState(false); const [queue,setQueue]=useState<Queue|null>(null); const [selected,setSelected]=useState<Review|null>(null); const [id,setId]=useState(""); const [loading,setLoading]=useState(false); const [inspectingId,setInspectingId]=useState<string|null>(null); const [removingId,setRemovingId]=useState<string|null>(null); const [error,setError]=useState(""); useEffect(()=>setMounted(true),[])
 const owner=uidData.status==="success"&&uidData.uid===config.ownerUid&&Boolean(uidData.accessToken)
 const load=useCallback(async()=>{if(!owner||!uidData.accessToken)return;setLoading(true);setError("");try{const r=await fetch("/api/operations/payment-review",{headers:{Authorization:`Bearer ${uidData.accessToken}`},cache:"no-store"});const d=await r.json();if(!r.ok||d?.available!==true)throw new Error(d?.error||"Workbench unavailable");setQueue(d)}catch(e){setQueue(null);setError(e instanceof Error?e.message:"Workbench unavailable")}finally{setLoading(false)}},[owner,uidData.accessToken]); useEffect(()=>{void load()},[load])
 const inspectPayment=async(paymentId:string)=>{if(!owner||!uidData.accessToken||!paymentId.trim())return;setInspectingId(paymentId);setError("");try{const r=await fetch(`/api/operations/payment-review?paymentId=${encodeURIComponent(paymentId.trim())}`,{headers:{Authorization:`Bearer ${uidData.accessToken}`},cache:"no-store"});const d=await r.json();if(!r.ok&&!d?.verdict)throw new Error(d?.error||"Review unavailable");setSelected(d)}catch(e){setError(e instanceof Error?e.message:"Review unavailable")}finally{setInspectingId(null)}}
 const inspect=async(e:FormEvent)=>{e.preventDefault();if(!id.trim())return;await inspectPayment(id.trim())}
 const remove=async(paymentId:string,canPrune:boolean)=>{if(!owner||!uidData.accessToken)return;if(!window.confirm(document.documentElement.lang === "ar" ? (canPrune?"إزالة هذا العنصر النهائي المثبت عدم تحرك أمواله من قائمة التشغيل؟ لن تُحذف السجلات المالية أو الأدلة.":"إزالة هذا العنصر الذي تمت مراجعته من عرض التشغيل؟ لن تتغير السجلات المالية أو فهارس التعافي أو معالجة التعافي.") : (canPrune?"Remove this proven terminal no-movement item from the operational queue? Financial records and evidence will NOT be deleted.":"Remove this reviewed item from the Operations view? Financial records, recovery indexes, and recovery processing will NOT be changed.")))return;setRemovingId(paymentId);setError("");try{const r=await fetch("/api/operations/payment-review",{method:"POST",headers:{Authorization:`Bearer ${uidData.accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({action:canPrune?"prune_terminal":"dismiss_reviewed",paymentId})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Queue removal unavailable");if(selected?.paymentId===paymentId)setSelected(null);setQueue(current=>{if(!current)return current;const items=current.items.filter(item=>item.paymentId!==paymentId);return {...current,items,counts:{total:items.length,recovering:items.filter(x=>x.verdict==="Recovering").length,manualReview:items.filter(x=>x.verdict==="Manual Review").length,conflicts:items.filter(x=>x.verdict==="Conflict").length,unknown:items.filter(x=>x.verdict==="Unknown").length,refunds:items.filter(x=>x.refund.state==="present").length}}})}catch(e){setError(e instanceof Error?e.message:"Queue removal unavailable")}finally{setRemovingId(null)}}
 if(!mounted||!owner)return null; const c=queue?.counts
 return <div className="min-h-screen bg-background p-4 pb-28"><div className="mx-auto max-w-5xl space-y-5"><BackButton/><div className="flex items-start justify-between gap-3"><div><h1 className="text-3xl font-bold">{tr('Recovery Command Center')}</h1><p className="mt-1 text-muted-foreground">{tr('Owner-only live workbench for recovery, refunds, conflicts and manual review.')}</p></div><Button variant="outline" size="sm" onClick={()=>void load()} disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}</Button></div>
 <div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{[["Open",c?.total],["Recovering",c?.recovering],["Review",c?.manualReview],["Conflict",c?.conflicts],["Unknown",c?.unknown],["Refunds",c?.refunds]].map(([k,v])=><Card key={String(k)}><CardContent className="p-3"><div className="text-xs text-muted-foreground">{k}</div><div className="text-2xl font-bold">{v??"—"}</div></CardContent></Card>)}</div>
 {error&&<Card className="border-red-400"><CardContent className="pt-6 text-sm text-red-600">{tr(error)}</CardContent></Card>}
 <Card><CardHeader><CardTitle>{tr('Live Recovery Queue')}</CardTitle><CardDescription>{tr('Discovered from the canonical active-recovery index. Final ordinary payments are not noise; refund evidence remains visible.')}</CardDescription></CardHeader><CardContent className="space-y-2">{!queue&&!loading?<p className="text-sm text-muted-foreground">{tr('Unavailable.')}</p>:queue?.items.length===0?<p className="text-sm text-muted-foreground">{tr('No active recovery or refund records are currently indexed.')}</p>:queue?.items.map(x=><div key={x.paymentId} className="w-full rounded-lg border p-3"><button onClick={()=>setSelected(x)} className="w-full text-left"><div className="flex items-center justify-between gap-2"><span className="break-all font-mono text-xs">{x.paymentId}</span><Badge className={badge(x.verdict)}>{x.verdict}</Badge></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><span>{tr("Status")} <b>{String(x.canonical.status??"—")}</b></span><span>{tr("Refund")} <b>{String(x.refund.status??x.refund.state??"—")}</b></span><span>{tr("Merchant")} <b>{String(x.parties.merchantId??"—")}</b></span><span>{tr("Amount")} <b>{String(x.canonical.customerAmount??"—")} π</b></span></div><p className="mt-2 text-xs text-muted-foreground">{tr(x.reason)}</p></button><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" disabled={inspectingId===x.paymentId} onClick={()=>void inspectPayment(x.paymentId)}>{inspectingId===x.paymentId?<><Loader2 className="mr-1 h-4 w-4 animate-spin"/>{tr('Inspecting…')}</>:tr("Inspect details")}</Button><Button type="button" variant="destructive" size="sm" disabled={removingId===x.paymentId} onClick={()=>void remove(x.paymentId,Boolean(x.action.canPruneFromQueue))}>{removingId===x.paymentId?<Loader2 className="mr-1 h-4 w-4 animate-spin"/>:<Trash2 className="mr-1 h-4 w-4"/>}{removingId===x.paymentId?"Removing…":x.action.canPruneFromQueue?"Remove from queue":tr("Remove from view")}</Button></div>{selected?.paymentId===x.paymentId&&<ReviewDetails review={selected}/>}</div>)}{queue?.note&&<p className="text-xs text-amber-700">{queue.note}</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Search className="h-5 w-5"/>{tr('Exact Payment Lookup')}</CardTitle><CardDescription>{tr('Optional deep lookup for any known FlashPay Payment ID.')}</CardDescription></CardHeader><CardContent><form onSubmit={inspect} className="flex gap-2"><input aria-label="Payment ID" value={id} onChange={e=>setId(e.target.value)} placeholder="Payment ID" className="min-w-0 flex-1 rounded-md border bg-background px-3 py-2 font-mono text-sm"/><Button disabled={Boolean(inspectingId)}>{inspectingId===id.trim()?<Loader2 className="h-4 w-4 animate-spin"/>:tr("Inspect")}</Button></form></CardContent></Card>
 {selected&&!queue?.items.some(x=>x.paymentId===selected.paymentId)&&<ReviewDetails review={selected}/>}
 </div></div>}
function ReviewDetails({review}:{review:Review}){return <div className="mt-4 space-y-4 border-t pt-4"><Card className={review.verdict==="Conflict"?"border-red-400":"border-amber-300"}><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle className="flex items-center gap-2">{review.verdict==="Final"?<CheckCircle2 className="h-5 w-5"/>:<AlertTriangle className="h-5 w-5"/>}{review.verdict}</CardTitle><Badge className={badge(review.verdict)}>{String(review.canonical.status??"Unknown")}</Badge></div><CardDescription>{tr(review.reason)}</CardDescription></CardHeader></Card><div className="grid gap-4 md:grid-cols-2"><Detail title="Parties" data={review.parties}/><Detail title="Canonical Financial State" data={review.canonical}/><Detail title="Refund Checkpoint" data={review.refund}/><Detail title="Database Cross-check" data={review.database}/></div><Card className="border-blue-300"><CardContent className="flex gap-3 pt-6"><ShieldCheck className="h-5 w-5 shrink-0 text-blue-600"/><div><b>{tr('Safe operator disposition')}</b><p className="mt-1 text-sm">{tr(review.action.message)}</p><p className="mt-2 text-xs text-muted-foreground">{tr('This console never deletes financial evidence, invents status, submits Horizon transactions, creates refunds, or bypasses wallet/recovery locks.')}</p></div></CardContent></Card></div>}
function Detail({title,data}:{title:string;data:Record<string,unknown>}){const e=Object.entries(data).filter(([,v])=>v!==null&&v!==undefined);return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-2">{e.map(([k,v])=><div key={k} className="rounded-md border p-2"><div className="text-xs text-muted-foreground">{k}</div><div className="break-all font-mono text-sm">{String(v)}</div></div>)}</CardContent></Card>}
