"use client"


const EXACT: Record<string, string> = {
  "Server-backed platform health with secondary device diagnostics":"صحة المنصة المدعومة من الخادم مع تشخيصات ثانوية للجهاز","Checking authoritative dependencies…":"جارٍ فحص الاعتماديات الموثوقة…","Waiting for server diagnostics…":"في انتظار تشخيص الخادم…","Overall:":"الإجمالي:","as of":"اعتبارًا من","Integration Domain Pages":"صفحات نطاقات التكامل","Revision":"المراجعة","Updated":"آخر تحديث",
  "FlashPay Owner Operations":"تشغيل FlashPay للمالك","Operational control plane":"طبقة التحكم التشغيلية","Operations":"التشغيل","Control":"التحكم","Profile":"الملف الشخصي","Testnet":"الشبكة التجريبية",
  "Access Denied":"تم رفض الوصول","You do not have permission to access the Operations Console.":"ليست لديك صلاحية للوصول إلى وحدة التحكم التشغيلية.","Return to Home":"العودة إلى الرئيسية",
  "Operations Console":"وحدة التحكم التشغيلية","Platform management and monitoring":"إدارة المنصة ومراقبتها","System Health":"صحة النظام","CHECKING":"جارٍ التحقق","UNKNOWN":"غير معروف","Healthy":"سليم","Degraded":"متدهور","Maintenance":"صيانة","Unknown":"غير معروف",
  "Settlement open":"تسويات مفتوحة","Failures":"الإخفاقات","Refund pending":"استرداد معلق","Manual review":"مراجعة يدوية","Recovery active":"تعافٍ نشط","Wallet ready":"المحفظة جاهزة","Worker wake":"استيقاظ العامل","Fresh":"حديث","Stale":"قديم","Online":"متصل","Offline":"غير متصل","Loading…":"جارٍ التحميل…","Refresh":"تحديث",
  "Financial Operations Health":"صحة العمليات المالية","Authoritative read-only settlement, refund, and recovery signals":"إشارات موثوقة للقراءة فقط عن التسوية والاسترداد والتعافي","Settled":"تمت التسوية","Settlement failed":"فشلت التسوية","Pi create pressure":"ضغط إنشاء Pi","ACTIVE":"نشط","Clear":"سليم",
  "System Diagnostics":"تشخيص النظام","Check health and troubleshoot issues":"فحص الصحة واستكشاف المشكلات","Run Diagnostics":"تشغيل التشخيص","Emergency Payment Recovery":"التعافي الطارئ للمدفوعات","Clear stuck pending payments securely":"معالجة المدفوعات المعلقة بأمان","If payments are stuck and blocking the system, use the emergency recovery page to clear them securely with owner authentication.":"إذا علقت المدفوعات وأعاقت النظام، فاستخدم صفحة التعافي الطارئ لمعالجتها بأمان بعد التحقق من المالك.","Go to Emergency Recovery":"الانتقال إلى التعافي الطارئ",
  "Server-authoritative availability · Redis-backed · owner verified":"إتاحة موثوقة من الخادم · مدعومة بـ Redis · المالك متحقق منه","Master lock is unchanged in Step 2. Its authoritative upgrade is Step 3.":"القفل الرئيسي لم يتغير في الخطوة 2. ترقيته الموثوقة ستكون في الخطوة 3.","Inactive":"غير نشط","Disable":"تعطيل","Enable":"تفعيل","Loading":"جارٍ التحميل","Owner authorization is required to read domain state.":"يلزم تحقق المالك لقراءة حالة النطاق.","Domain state unavailable":"حالة النطاق غير متاحة","Domain control change failed":"فشل تغيير التحكم في النطاق","Domain Management":"إدارة النطاقات","Configure integration domains":"تهيئة نطاقات التكامل","Configure integration domains and access controls":"تهيئة نطاقات التكامل وضوابط الوصول","Server-authoritative safety gate for domain-control writes. Locking it never stops FlashPay; it only prevents domain Enable/Disable changes.":"بوابة أمان موثوقة من الخادم لتغييرات التحكم في النطاق. قفلها لا يوقف FlashPay؛ بل يمنع فقط تغييرات تفعيل أو تعطيل النطاق.","Lock domain controls":"قفل التحكم في النطاق","Unlock domain controls":"فتح التحكم في النطاق","Master lock change failed":"فشل تغيير القفل الرئيسي","Master Lock":"القفل الرئيسي","Unlocked":"مفتوح","Locked":"مقفل","Master lock controls access to all integration domains":"يتحكم القفل الرئيسي في الوصول إلى جميع نطاقات التكامل","Domains":"النطاقات","Primary":"رئيسي","Active":"نشط","Disabled":"معطل","Integration Domain Pages":"صفحات نطاقات التكامل","Access domain-specific operational pages":"الوصول إلى صفحات التشغيل الخاصة بالنطاق",
  "Control Panel":"لوحة التحكم","System operations and emergency kill switch":"تشغيل النظام ومفتاح الإيقاف الطارئ","Open Control Panel":"فتح لوحة التحكم","Owner control plane · operational authority only":"طبقة تحكم المالك · صلاحية تشغيلية فقط","Loading authoritative control state...":"جارٍ تحميل حالة التحكم الموثوقة...","Authoritative Control State":"حالة التحكم الموثوقة","Server-verified owner read · Redis-backed state":"قراءة مالك متحقق منها من الخادم · حالة مدعومة بـ Redis","Application control":"التحكم في التطبيق","Maintenance control active":"تحكم الصيانة نشط","Normal operation":"تشغيل طبيعي","OFFLINE":"غير متصل","ONLINE":"متصل","Revision":"المراجعة","Updated":"آخر تحديث","Control state is unknown. Writes are blocked.":"حالة التحكم غير معروفة. عمليات الكتابة محظورة.","Refresh canonical state":"تحديث الحالة المرجعية",
  "Change justification":"مبرر التغيير","Required for every control write and stored in the operational audit trail.":"مطلوب لكل تغيير في التحكم ويُحفظ في سجل التدقيق التشغيلي.","Operational change justification":"مبرر التغيير التشغيلي","Why is this operational change necessary?":"لماذا هذا التغيير التشغيلي ضروري؟","Emergency Kill Switch":"مفتاح الإيقاف الطارئ","High-impact application availability control. It does not alter payment, settlement, refund, Horizon, DB, or accounting truth.":"تحكم عالي التأثير في إتاحة التطبيق. لا يغيّر حقيقة الدفع أو التسوية أو الاسترداد أو Horizon أو قاعدة البيانات أو المحاسبة.","Activate":"تفعيل","Deactivate":"إلغاء التفعيل","Restore Control Defaults":"استعادة إعدادات التحكم الافتراضية","Restores only the operational control-state record. It does not reset FlashPay, payments, financial records, recovery, or user data.":"يستعيد سجل حالة التحكم التشغيلي فقط. ولا يعيد ضبط FlashPay أو المدفوعات أو السجلات المالية أو التعافي أو بيانات المستخدم.","This is deliberately not called “System Reset”: its authority is limited to the control-state record.":"لا يُسمى هذا عمدًا «إعادة ضبط النظام»: فصلاحياته مقصورة على سجل حالة التحكم.","This control remains available whenever the authoritative state is readable. A justification and RESTORE confirmation are still required before any write.":"يظل هذا التحكم متاحًا متى كانت الحالة الموثوقة قابلة للقراءة. ويظل إدخال المبرر وتأكيد RESTORE مطلوبين قبل أي كتابة.","Enter an operational reason before changing control state.":"أدخل سببًا تشغيليًا قبل تغيير حالة التحكم.",
  "Infrastructure Health":"صحة البنية التحتية","Re-run":"إعادة الفحص","Owner-authenticated, read-only checks. Unknown is never reported as healthy.":"فحوصات للقراءة فقط مع تحقق المالك. لا تُعرض الحالة المجهولة مطلقًا على أنها سليمة.","Infrastructure diagnostics unavailable. No healthy state is inferred.":"تشخيص البنية التحتية غير متاح. لا يتم افتراض حالة سليمة.","Observed:":"تم الرصد:","Device Diagnostics":"تشخيص الجهاز","Browser/device checks only; these do not prove platform or financial health.":"فحوصات المتصفح والجهاز فقط؛ ولا تثبت صحة المنصة أو الحالة المالية.","Pi SDK is available":"حزمة Pi SDK متاحة","Pi SDK not detected":"لم يتم اكتشاف حزمة Pi SDK","Local Storage":"التخزين المحلي","Local Storage is accessible":"التخزين المحلي متاح","Local Storage is restricted":"التخزين المحلي مقيّد","Network":"الشبكة","Browser reports online":"المتصفح يفيد بوجود اتصال","Browser reports offline":"المتصفح يفيد بعدم وجود اتصال",
  "Recovery Command Center":"مركز قيادة التعافي","Owner-only live workbench for recovery, refunds, conflicts and manual review.":"مساحة عمل مباشرة للمالك فقط للتعافي والاستردادات والتعارضات والمراجعة اليدوية.","Open":"مفتوح","Recovering":"قيد التعافي","Review":"مراجعة","Conflict":"تعارض","Refunds":"الاستردادات","Live Recovery Queue":"قائمة انتظار التعافي المباشرة","Unavailable.":"غير متاح.","No active recovery or refund records are currently indexed.":"لا توجد حاليًا سجلات تعافٍ أو استرداد نشطة مفهرسة.","Status":"الحالة","Refund":"الاسترداد","Merchant":"التاجر","Amount":"المبلغ","Inspect details":"فحص التفاصيل","Inspecting…":"جارٍ الفحص…","Removing…":"جارٍ الإزالة…","Remove from queue":"إزالة من القائمة","Remove from view":"إزالة من العرض","Exact Payment Lookup":"بحث دقيق عن دفعة","Optional deep lookup for any known FlashPay Payment ID.":"بحث تفصيلي اختياري عن أي معرّف دفع FlashPay معروف.","Payment ID":"معرّف الدفع","Inspect":"فحص","Final":"نهائي","Manual Review":"مراجعة يدوية","Parties":"الأطراف","Canonical Financial State":"الحالة المالية المرجعية","Refund Checkpoint":"نقطة تحقق الاسترداد","Database Cross-check":"مطابقة قاعدة البيانات","Safe operator disposition":"إجراء المشغّل الآمن",
  "Financial health is unavailable. No healthy state is inferred.":"الصحة المالية غير متاحة. لا يتم افتراض حالة سليمة.","Loading authoritative financial health…":"جارٍ تحميل الصحة المالية الموثوقة…","Loading authoritative platform overview…":"جارٍ تحميل نظرة المنصة الموثوقة…","Authoritative platform overview unavailable":"نظرة المنصة الموثوقة غير متاحة","Merchants":"التجار","Payments":"المدفوعات","Volume":"الحجم",
  "Every write performs fresh server-side owner verification and rejects a stale control revision. You must type the requested confirmation phrase.":"تخضع كل عملية كتابة لتحقق جديد من هوية المالك على الخادم، وتُرفض أي مراجعة تحكم قديمة. ويجب كتابة عبارة التأكيد المطلوبة.",
  "CONTROL PLANE MAY OBSERVE FINANCIAL TRUTH; IT MUST NEVER INVENT OR BYPASS FINANCIAL TRUTH.":"يجوز لطبقة التحكم مراقبة الحقيقة المالية، ولا يجوز لها مطلقًا اختلاق الحقيقة المالية أو تجاوزها.",
  "Reading authoritative operational evidence…":"جارٍ قراءة الأدلة التشغيلية الموثوقة…","Authoritative incident health is unavailable":"صحة الحوادث التشغيلية الموثوقة غير متاحة","One or more authoritative operational reads are unavailable":"قراءة تشغيلية موثوقة واحدة أو أكثر غير متاحة","Kill switch is enabled":"مفتاح الإيقاف مفعّل","Operational attention is required":"توجد حالة تشغيلية تتطلب الانتباه","Authoritative operational signals are within normal bounds":"الإشارات التشغيلية الموثوقة ضمن الحدود الطبيعية",
  "Workbench unavailable":"مساحة عمل التعافي غير متاحة","Review unavailable":"المراجعة غير متاحة","Queue removal unavailable":"إزالة العنصر من قائمة التشغيل غير متاحة","Operational review unavailable":"المراجعة التشغيلية غير متاحة","Canonical Redis unavailable":"Redis المرجعي غير متاح","Invalid Payment ID":"معرّف الدفع غير صالح","Payment not found in canonical Redis":"لم يتم العثور على الدفعة في Redis المرجعي","Invalid operator action":"إجراء المشغّل غير صالح","Canonical payment not found":"لم يتم العثور على الدفعة المرجعية","Queue removal is blocked because terminal no-movement evidence is not proven":"إزالة العنصر من القائمة محظورة لأن دليل الحالة النهائية دون حركة أموال غير مثبت","Invalid queue removal result":"نتيجة إزالة العنصر من القائمة غير صالحة","Operator action unavailable":"إجراء المشغّل غير متاح",
  "Evidence is insufficient for an automatic conclusion":"الأدلة غير كافية للوصول إلى نتيجة تلقائية","Settlement and refund evidence coexist; financial action is blocked":"توجد أدلة تسوية واسترداد معًا؛ الإجراء المالي محظور","Canonical finality proof is complete":"دليل النهائية المرجعي مكتمل","One or more authoritative reads are uncertain":"قراءة موثوقة واحدة أو أكثر غير مؤكدة","Canonical state requires manual review":"الحالة المرجعية تتطلب مراجعة يدوية","Non-final state is owned by existing recovery authorities":"الحالة غير النهائية تخضع لسلطات التعافي القائمة","Settlement failed without a proven safe manual action":"فشلت التسوية دون وجود إجراء يدوي آمن ومثبت",
  "No action required.":"لا يلزم أي إجراء.","Recovery is automatic. Manual execution is intentionally unavailable while the authoritative recovery path owns this payment.":"التعافي تلقائي. التنفيذ اليدوي غير متاح عمدًا ما دام مسار التعافي الموثوق مسؤولًا عن هذه الدفعة.","No financial action is exposed until the existing Plan 7 authority can prove a safe transition. Unknown/conflict always fails closed.":"لا يتاح أي إجراء مالي حتى تثبت سلطة الخطة 7 القائمة انتقالًا آمنًا. الحالة المجهولة أو المتعارضة تُغلق دائمًا بأمان.",
  "Discovered from the canonical active-recovery index. Final ordinary payments are not noise; refund evidence remains visible.":"مستخرجة من فهرس التعافي النشط المرجعي. المدفوعات النهائية العادية لا تُعامل كضوضاء؛ وتظل أدلة الاسترداد ظاهرة.","This console never deletes financial evidence, invents status, submits Horizon transactions, creates refunds, or bypasses wallet/recovery locks.":"هذه الوحدة لا تحذف الأدلة المالية، ولا تختلق حالة، ولا ترسل معاملات Horizon، ولا تنشئ استردادات، ولا تتجاوز أقفال المحفظة أو التعافي.","Showing the first 250 active recovery records.":"يتم عرض أول 250 سجل تعافٍ نشط."
}

const WORDS: Array<[RegExp,string]> = [
  [/\bdomains enabled\b/gi,"نطاقات مفعّلة"],[/\bas of\b/gi,"حتى"],[/\blast wake\b/gi,"آخر استيقاظ"],[/\bdrain lease\b/gi,"قفل التصريف"],[/\bactive\b/gi,"نشط"],[/\bidle\b/gi,"خامل"],[/\bpass\b/gi,"ناجح"],[/\bfail\b/gi,"فشل"],[/\bwarn\b/gi,"تحذير"],[/\bunknown\b/gi,"غير معروف"],[/\bcomplete\b/gi,"مكتمل"],[/\bpayment\b/gi,"الدفع"],[/\brefund\b/gi,"الاسترداد"],[/\bstatus\b/gi,"الحالة"]
]

export function translateUpperOperationsText(locale: string, value: string): string {
  if (locale !== "ar") return value
  const trimmed = value.trim()
  if (!trimmed) return value
  let translated = EXACT[trimmed] ?? trimmed
  if (translated === trimmed) {
    for (const [pattern, replacement] of WORDS) translated = translated.replace(pattern, replacement)
  }
  return translated === trimmed ? value : value.replace(trimmed, translated)
}
