"use client"

import { useEffect } from "react"
import { usePathname } from "next/navigation"
import { useI18n } from "@/components/i18n-provider"

const EXACT: Record<string, string> = {
  "FlashPay Owner Operations":"تشغيل FlashPay للمالك","Operational control plane":"طبقة التحكم التشغيلية","Operations":"التشغيل","Control":"التحكم","Profile":"الملف الشخصي","Testnet":"الشبكة التجريبية",
  "Access Denied":"تم رفض الوصول","You do not have permission to access the Operations Console.":"ليست لديك صلاحية للوصول إلى وحدة التحكم التشغيلية.","Return to Home":"العودة إلى الرئيسية",
  "Operations Console":"وحدة التحكم التشغيلية","Platform management and monitoring":"إدارة المنصة ومراقبتها","System Health":"صحة النظام","CHECKING":"جارٍ التحقق","UNKNOWN":"غير معروف","Healthy":"سليم","Degraded":"متدهور","Maintenance":"صيانة","Unknown":"غير معروف",
  "Settlement open":"تسويات مفتوحة","Failures":"الإخفاقات","Refund pending":"استرداد معلق","Manual review":"مراجعة يدوية","Recovery active":"تعافٍ نشط","Wallet ready":"المحفظة جاهزة","Worker wake":"استيقاظ العامل","Fresh":"حديث","Stale":"قديم","Online":"متصل","Offline":"غير متصل","Loading…":"جارٍ التحميل…","Refresh":"تحديث",
  "Financial Operations Health":"صحة العمليات المالية","Authoritative read-only settlement, refund, and recovery signals":"إشارات موثوقة للقراءة فقط عن التسوية والاسترداد والتعافي","Settled":"تمت التسوية","Settlement failed":"فشلت التسوية","Pi create pressure":"ضغط إنشاء Pi","ACTIVE":"نشط","Clear":"سليم",
  "System Diagnostics":"تشخيص النظام","Check health and troubleshoot issues":"فحص الصحة واستكشاف المشكلات","Run Diagnostics":"تشغيل التشخيص","Emergency Payment Recovery":"التعافي الطارئ للمدفوعات","Clear stuck pending payments securely":"معالجة المدفوعات المعلقة بأمان","If payments are stuck and blocking the system, use the emergency recovery page to clear them securely with owner authentication.":"إذا علقت المدفوعات وأعاقت النظام، فاستخدم صفحة التعافي الطارئ لمعالجتها بأمان بعد التحقق من المالك.","Go to Emergency Recovery":"الانتقال إلى التعافي الطارئ",
  "Domain Management":"إدارة النطاقات","Configure integration domains":"تهيئة نطاقات التكامل","Configure integration domains and access controls":"تهيئة نطاقات التكامل وضوابط الوصول","Master Lock":"القفل الرئيسي","Unlocked":"مفتوح","Locked":"مقفل","Master lock controls access to all integration domains":"يتحكم القفل الرئيسي في الوصول إلى جميع نطاقات التكامل","Domains":"النطاقات","Primary":"رئيسي","Active":"نشط","Disabled":"معطل","Integration Domain Pages":"صفحات نطاقات التكامل","Access domain-specific operational pages":"الوصول إلى صفحات التشغيل الخاصة بالنطاق",
  "Control Panel":"لوحة التحكم","System operations and emergency kill switch":"تشغيل النظام ومفتاح الإيقاف الطارئ","Open Control Panel":"فتح لوحة التحكم","Owner control plane · operational authority only":"طبقة تحكم المالك · صلاحية تشغيلية فقط","Loading authoritative control state...":"جارٍ تحميل حالة التحكم الموثوقة...","Authoritative Control State":"حالة التحكم الموثوقة","Server-verified owner read · Redis-backed state":"قراءة مالك متحقق منها من الخادم · حالة مدعومة بـ Redis","Application control":"التحكم في التطبيق","Maintenance control active":"تحكم الصيانة نشط","Normal operation":"تشغيل طبيعي","OFFLINE":"غير متصل","ONLINE":"متصل","Revision":"المراجعة","Updated":"آخر تحديث","Control state is unknown. Writes are blocked.":"حالة التحكم غير معروفة. عمليات الكتابة محظورة.","Refresh canonical state":"تحديث الحالة المرجعية",
  "Change justification":"مبرر التغيير","Required for every control write and stored in the operational audit trail.":"مطلوب لكل تغيير في التحكم ويُحفظ في سجل التدقيق التشغيلي.","Operational change justification":"مبرر التغيير التشغيلي","Why is this operational change necessary?":"لماذا هذا التغيير التشغيلي ضروري؟","Emergency Kill Switch":"مفتاح الإيقاف الطارئ","High-impact application availability control. It does not alter payment, settlement, refund, Horizon, DB, or accounting truth.":"تحكم عالي التأثير في إتاحة التطبيق. لا يغيّر حقيقة الدفع أو التسوية أو الاسترداد أو Horizon أو قاعدة البيانات أو المحاسبة.","Activate":"تفعيل","Deactivate":"إلغاء التفعيل","Restore Control Defaults":"استعادة إعدادات التحكم الافتراضية","Restores only the operational control-state record. It does not reset FlashPay, payments, financial records, recovery, or user data.":"يستعيد سجل حالة التحكم التشغيلي فقط. ولا يعيد ضبط FlashPay أو المدفوعات أو السجلات المالية أو التعافي أو بيانات المستخدم.","This is deliberately not called “System Reset”: its authority is limited to the control-state record.":"لا يُسمى هذا عمدًا «إعادة ضبط النظام»: فصلاحياته مقصورة على سجل حالة التحكم.",
  "Infrastructure Health":"صحة البنية التحتية","Re-run":"إعادة الفحص","Owner-authenticated, read-only checks. Unknown is never reported as healthy.":"فحوصات للقراءة فقط مع تحقق المالك. لا تُعرض الحالة المجهولة مطلقًا على أنها سليمة.","Infrastructure diagnostics unavailable. No healthy state is inferred.":"تشخيص البنية التحتية غير متاح. لا يتم افتراض حالة سليمة.","Observed:":"تم الرصد:","Device Diagnostics":"تشخيص الجهاز","Browser/device checks only; these do not prove platform or financial health.":"فحوصات المتصفح والجهاز فقط؛ ولا تثبت صحة المنصة أو الحالة المالية.","Pi SDK is available":"حزمة Pi SDK متاحة","Pi SDK not detected":"لم يتم اكتشاف حزمة Pi SDK","Local Storage":"التخزين المحلي","Local Storage is accessible":"التخزين المحلي متاح","Local Storage is restricted":"التخزين المحلي مقيّد","Network":"الشبكة","Browser reports online":"المتصفح يفيد بوجود اتصال","Browser reports offline":"المتصفح يفيد بعدم وجود اتصال",
  "Recovery Command Center":"مركز قيادة التعافي","Owner-only live workbench for recovery, refunds, conflicts and manual review.":"مساحة عمل مباشرة للمالك فقط للتعافي والاستردادات والتعارضات والمراجعة اليدوية.","Open":"مفتوح","Recovering":"قيد التعافي","Review":"مراجعة","Conflict":"تعارض","Refunds":"الاستردادات","Live Recovery Queue":"قائمة انتظار التعافي المباشرة","Unavailable.":"غير متاح.","No active recovery or refund records are currently indexed.":"لا توجد حاليًا سجلات تعافٍ أو استرداد نشطة مفهرسة.","Status":"الحالة","Refund":"الاسترداد","Merchant":"التاجر","Amount":"المبلغ","Inspect details":"فحص التفاصيل","Inspecting…":"جارٍ الفحص…","Removing…":"جارٍ الإزالة…","Remove from queue":"إزالة من القائمة","Remove from view":"إزالة من العرض","Exact Payment Lookup":"بحث دقيق عن دفعة","Optional deep lookup for any known FlashPay Payment ID.":"بحث تفصيلي اختياري عن أي معرّف دفع FlashPay معروف.","Payment ID":"معرّف الدفع","Inspect":"فحص","Final":"نهائي","Manual Review":"مراجعة يدوية","Parties":"الأطراف","Canonical Financial State":"الحالة المالية المرجعية","Refund Checkpoint":"نقطة تحقق الاسترداد","Database Cross-check":"مطابقة قاعدة البيانات","Safe operator disposition":"إجراء المشغّل الآمن",
  "Financial health is unavailable. No healthy state is inferred.":"الصحة المالية غير متاحة. لا يتم افتراض حالة سليمة.","Loading authoritative financial health…":"جارٍ تحميل الصحة المالية الموثوقة…","Loading authoritative platform overview…":"جارٍ تحميل نظرة المنصة الموثوقة…","Authoritative platform overview unavailable":"نظرة المنصة الموثوقة غير متاحة","Merchants":"التجار","Payments":"المدفوعات","Volume":"الحجم"
}

const WORDS: Array<[RegExp,string]> = [
  [/\bdomains enabled\b/gi,"نطاقات مفعّلة"],[/\bas of\b/gi,"حتى"],[/\blast wake\b/gi,"آخر استيقاظ"],[/\bdrain lease\b/gi,"قفل التصريف"],[/\bactive\b/gi,"نشط"],[/\bidle\b/gi,"خامل"],[/\bpass\b/gi,"ناجح"],[/\bfail\b/gi,"فشل"],[/\bwarn\b/gi,"تحذير"],[/\bunknown\b/gi,"غير معروف"],[/\bcomplete\b/gi,"مكتمل"],[/\bpayment\b/gi,"الدفع"],[/\brefund\b/gi,"الاسترداد"],[/\bstatus\b/gi,"الحالة"]
]

const SCOPES = ["/operations", "/control-panel", "/diagnostics", "/emergency"]
const originals = new WeakMap<Text, string>()
const attrOriginals = new WeakMap<Element, Record<string,string>>()

function translate(value:string){const trimmed=value.trim(); if(!trimmed)return value; let out=EXACT[trimmed] ?? trimmed; if(out===trimmed) for(const [re,to] of WORDS) out=out.replace(re,to); if(out===trimmed)return value; return value.replace(trimmed,out)}

export function UpperOperationsArabicLayer(){
  const pathname=usePathname(); const {locale}=useI18n(); const scoped=SCOPES.some(p=>pathname===p||pathname.startsWith(`${p}/`))
  useEffect(()=>{
    if(!scoped)return
    const root=document.body
    const apply=()=>{
      const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let node:Node|null
      while((node=walker.nextNode())){const t=node as Text; const parent=t.parentElement; if(!parent||["SCRIPT","STYLE","CODE"].includes(parent.tagName))continue; if(!originals.has(t)) originals.set(t,t.nodeValue??""); const base=originals.get(t)??""; const next=locale==="ar"?translate(base):base; if(t.nodeValue!==next)t.nodeValue=next}
      root.querySelectorAll("[placeholder],[aria-label],[title]").forEach(el=>{let saved=attrOriginals.get(el); if(!saved){saved={}; for(const a of ["placeholder","aria-label","title"]){const v=el.getAttribute(a);if(v)saved[a]=v} attrOriginals.set(el,saved)} for(const [a,v] of Object.entries(saved)){const next=locale==="ar"?translate(v):v;if(el.getAttribute(a)!==next)el.setAttribute(a,next)}})
    }
    apply(); const observer=new MutationObserver(apply); observer.observe(root,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["placeholder","aria-label","title"]}); return()=>observer.disconnect()
  },[locale,scoped])
  return null
}
