import type { FinancialRecoveryCrashEffect, FinancialRecoveryCrashWindow } from "./financial-recovery-crash-window"
import type { EvidencedState } from "./financial-recovery-evidence"
import type { FinancialRecoveryReconciliationSource } from "./financial-recovery-decision"

export type FinancialRecoveryCrashTargetState = EvidencedState | "u2a_approved" | "u2a_cancelled_unmoved"
export type FinancialRecoveryCrashRetryAuthority = "NEVER" | "CONFIRMED_NONE"
export type FinancialRecoveryCrashPrimaryPath = "RECONCILE_FIRST" | "RESUME_NON_FINANCIAL" | "FAIL_CLOSED"

export type FinancialRecoveryCrashPolicy = {
  readonly precedingEffect: FinancialRecoveryCrashEffect
  readonly recoveryTargetState: FinancialRecoveryCrashTargetState
  readonly onTargetReached: "NO_ACTION"
  readonly onUncertainty: "MANUAL_REVIEW"
  readonly onConflict: "MANUAL_REVIEW"
  readonly evidenceBeforeAction: true
  readonly retryAuthority: FinancialRecoveryCrashRetryAuthority
  readonly primaryPath: FinancialRecoveryCrashPrimaryPath
  readonly reconciliationSource: FinancialRecoveryReconciliationSource | null
}

export type FinancialRecoveryCrashPolicyMatrix = Readonly<Record<FinancialRecoveryCrashWindow, FinancialRecoveryCrashPolicy>>

export const FINANCIAL_RECOVERY_CRASH_POLICY_MATRIX = {
  u2a_approval_ownership_checkpoint_before_attempt_claim: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "u2a_approved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_approval_attempt_claimed_before_pi_approve: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "u2a_approved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_pi_approved_before_approval_reconciliation: { precedingEffect: "PI_STATE_CHANGED", recoveryTargetState: "u2a_approved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_verified_checkpoint_before_complete_attempt: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "app_funds_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_complete_attempt_claimed_before_pi_complete: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "app_funds_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_pi_complete_before_durable_completion_checkpoint: { precedingEffect: "PI_STATE_CHANGED", recoveryTargetState: "app_funds_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_durable_completion_before_redis_projection: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "app_funds_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  u2a_redis_checkpoint_before_a2u_dispatch: { precedingEffect: "LOCAL_ONLY", recoveryTargetState: "settlement_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_cancel_attempt_claimed_before_pi_cancel: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "u2a_cancelled_unmoved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  u2a_pi_cancelled_before_durable_retirement: { precedingEffect: "PI_STATE_CHANGED", recoveryTargetState: "u2a_cancelled_unmoved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  settlement_create_attempt_claimed_before_pi_create: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  settlement_create_returned_before_id_checkpoint: { precedingEffect: "PAYMENT_CREATED", recoveryTargetState: "settlement_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  settlement_redis_prepared_before_durable_prepared_checkpoint: { precedingEffect: "LOCAL_ONLY", recoveryTargetState: "settlement_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "FAIL_CLOSED", reconciliationSource: null },
  settlement_durable_prepared_checkpoint_before_horizon_submit: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_blockchain_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "HORIZON" },
  settlement_horizon_confirmed_before_txid_checkpoint: { precedingEffect: "MONEY_MOVED", recoveryTargetState: "settlement_blockchain_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "HORIZON" },
  settlement_txid_checkpoint_before_pi_complete: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  settlement_a2u_complete_attempt_claimed_before_pi_complete: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  settlement_pi_complete_before_completion_checkpoint: { precedingEffect: "PI_STATE_CHANGED", recoveryTargetState: "settlement_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  settlement_completion_checkpoint_before_accounting: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  settlement_accounting_checkpoint_before_db_commit: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  settlement_db_commit_before_final_checkpoint: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "settlement_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  refund_eligibility_checkpoint_before_intent_transition: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_intent_checkpoint_before_submission_attempt: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_submission_attempt_before_pi_create: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_create_attempt_claimed_before_pi_create: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_pi_create_verified_before_payment_id_checkpoint: { precedingEffect: "PAYMENT_CREATED", recoveryTargetState: "refund_created", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_payment_id_checkpoint_before_horizon_claim: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_blockchain_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "HORIZON" },
  refund_horizon_claim_before_blockchain_submit: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_blockchain_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "HORIZON" },
  refund_horizon_confirmed_before_txid_checkpoint: { precedingEffect: "MONEY_MOVED", recoveryTargetState: "refund_blockchain_confirmed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "HORIZON" },
  refund_txid_checkpoint_before_pi_complete: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "CONFIRMED_NONE", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_complete_attempt_claimed_before_pi_complete: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_pi_complete_before_payment_projection: { precedingEffect: "PI_STATE_CHANGED", recoveryTargetState: "refund_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_payment_projection_before_checkpoint_advance: { precedingEffect: "LOCAL_ONLY", recoveryTargetState: "refund_pi_completed", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  refund_payment_checkpoint_updated_before_accounting_record: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  refund_accounting_record_before_accounting_checkpoint: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  refund_accounting_checkpoint_before_audit_checkpoint: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  refund_audit_checkpoint_before_completion_checkpoint: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  refund_completion_checkpoint_before_final_projection: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "refund_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  refund_final_projection_before_finality_audit: { precedingEffect: "LOCAL_ONLY", recoveryTargetState: "refund_finalized", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RESUME_NON_FINANCIAL", reconciliationSource: null },
  dr11_a2u_cancel_attempt_claimed_before_pi_cancel: { precedingEffect: "DB_COMMITTED", recoveryTargetState: "u2a_cancelled_unmoved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
  dr11_a2u_pi_cancelled_before_refund_containment: { precedingEffect: "PI_STATE_CHANGED", recoveryTargetState: "u2a_cancelled_unmoved", onTargetReached: "NO_ACTION", onUncertainty: "MANUAL_REVIEW", onConflict: "MANUAL_REVIEW", evidenceBeforeAction: true, retryAuthority: "NEVER", primaryPath: "RECONCILE_FIRST", reconciliationSource: "PI_PAYMENT" },
} as const satisfies FinancialRecoveryCrashPolicyMatrix
