import fs from "node:fs"
const need=(v:unknown,m:string)=>{if(!v)throw new Error(m)}
const h=fs.readFileSync("lib/fin4-live-certification.ts","utf8")
const a=fs.readFileSync("lib/a2u-executor.ts","utf8")
const t=fs.readFileSync("app/api/certification/fin4-trigger/route.ts","utf8")
need(h.includes('process.env.VERCEL_ENV !== "production" || process.env.FLASHPAY_FIN4_ARMED !== "1"'),"FIN4 must be production+explicit-arm gated")
need(h.includes('paymentA === paymentB'),"FIN4 must reject identical payments")
need(h.includes('aProcess !== bProcess && aWallet === sourceWallet && bWallet === sourceWallet'),"FIN4 barrier must require distinct processes and same source wallet")
need(h.includes('FIN4_FAIL_CLOSED_DISTINCT_PROCESS_BARRIER_TIMEOUT'),"FIN4 barrier must fail closed")
need(h.includes('flashpay:cert:fin4:v1:'),"FIN4 telemetry must be namespaced away from financial truth")
need(!h.includes('submitTransaction(') && !h.includes('claimPiWalletIntent(') && !h.includes('releasePiWalletIntent('),"FIN4 harness must have no financial authority")
const barrier=a.indexOf('fin4BeforeWalletLock(ctx.paymentId, appPublicKey)')
const lock=a.indexOf('acquirePiWalletIntentSubmitLock(appPublicKey',barrier)
const submit=a.indexOf('moveStage2UnderHeldWalletLock(horizonServer, transaction, preparedHash)',lock)
need(barrier>=0&&lock>barrier&&submit>lock,"FIN4 must observe real production lock then real submit")
need(a.includes('fin4Event(ctx.paymentId, appPublicKey, fin4State, walletLock ? "LOCK_ACQUIRED"'),"FIN4 lock outcome telemetry missing")
need(a.includes('fin4Event(ctx.paymentId, appPublicKey, fin4State, "SUBMIT_ENTER"'),"FIN4 pre-submit telemetry missing")
need(a.includes('fin4BestEffortEvent(ctx.paymentId, appPublicKey, fin4State, "SUBMIT_VERIFIED"'),"FIN4 post-movement telemetry must be best-effort")
const verified=a.indexOf('fin4BestEffortEvent(ctx.paymentId, appPublicKey, fin4State, "SUBMIT_VERIFIED"')
const durable=a.indexOf('recordSettlementHorizonCheckpoint({',verified)
need(verified>=0&&durable>verified,"durable Horizon checkpoint must remain after nonthrowing post-movement telemetry")
const releasing=a.indexOf('fin4BestEffortEvent(ctx.paymentId, ctx.payment.a2uFromAddress, fin4State, "LOCK_RELEASING")')
const release=a.indexOf('await walletLock.release()',releasing)
const released=a.indexOf('fin4BestEffortEvent(ctx.paymentId, ctx.payment.a2uFromAddress, fin4State, "LOCK_RELEASED")',release)
need(releasing>=0&&release>releasing&&released>release,"wallet release must be independent of best-effort telemetry")
need(t.includes('x-flashpay-fin4-run-id')&&t.includes('timingSafeEqual'),"FIN4 trigger must authenticate exact armed run id")
need(t.includes('fin4ArmedPaymentForRole(runId, body.role)')&&!t.includes('body.paymentId'),"FIN4 trigger must derive payment only from armed env A/B")
need(t.includes('executeA2URecovery(paymentId)'),"FIN4 trigger must delegate to existing recovery path")
need(!t.includes('submitTransaction(')&&!t.includes('A2U_INTERNAL_SECRET'),"FIN4 trigger must not implement financial submit or expose internal secret")
console.log("FIN4_LIVE_CERTIFICATION_HARNESS_R2=PASS financial_authority=false distinct_process_barrier=true fail_closed=true post_movement_telemetry_nonblocking=true wallet_release_nonblocking=true targeted_trigger=true")
