import { readFileSync } from "node:fs"
import { resolve } from "node:path"

const must=(ok:boolean,msg:string)=>{if(!ok)throw new Error(`PLAN_H_CRASH_POLICY_BINDING=FAIL ${msg}`)}
const complete=readFileSync(resolve(__dirname,"../app/api/pi/complete/route.ts"),"utf8")
const locked=readFileSync(resolve(__dirname,"../lib/a2u-locked-executor.ts"),"utf8")
const refund=readFileSync(resolve(__dirname,"../lib/refund-blockchain-submit.ts"),"utf8")
const crashSource=readFileSync(resolve(__dirname,"../lib/financial-recovery-crash-window.ts"),"utf8")
const crashList=crashSource.slice(crashSource.indexOf("export const FINANCIAL_RECOVERY_CRASH_WINDOWS"),crashSource.indexOf("] as const"))
const modeledWindows=(crashList.match(/^\s*"[a-z0-9_]+",$/gm)||[]).length
must(modeledWindows===41,"FIN-7 canonical crash-window set must remain exactly 41")
const verifiedAt=complete.indexOf("await recordSettlementU2AVerifiedCheckpoint(")
const completePostAt=complete.indexOf('fetch(`https://api.minepi.com/v2/payments/${piPaymentId}/complete`')
const postCatchAt=complete.indexOf("Pi /complete transport outcome ambiguous; reconciling exact payment")
const refetchAt=complete.indexOf('fetch(`https://api.minepi.com/v2/payments/${piPaymentId}`,',completePostAt)
const completedAt=complete.indexOf("await recordSettlementU2ACompletedCheckpoint(")
const projectionAt=complete.indexOf("await persist",completedAt)
must(verifiedAt>=0&&completePostAt>verifiedAt,"U2A verified durable checkpoint must precede Pi complete side effect")
must(postCatchAt>completePostAt&&refetchAt>postCatchAt,"Pi complete exception/non-OK must converge on exact GET reconciliation")
must(!complete.slice(completePostAt,refetchAt).includes('return NextResponse.json({ error: "Payment completion failed"'),"Pi complete ambiguity must not return before refetch")
must(completedAt>refetchAt,"durable U2A completed checkpoint must follow exact Pi reconciliation")

const submitBranch=locked.indexOf('if (params.recoveryOperation === "SETTLEMENT_SUBMIT")')
const preReplayAt=locked.indexOf("await executeFinancialRecoverySettlementSubmitReplay({ payment: latestPayment, paymentId })",submitBranch)
const movementAt=locked.indexOf('if (replay.outcome === "MOVEMENT_VERIFIED")',preReplayAt)
const preReplayDurable=locked.indexOf("await recordSettlementHorizonCheckpoint({",movementAt)
const allowReplayAt=locked.indexOf('if (replay.outcome !== "ALLOW_EXACT_REPLAY"',movementAt)
const preReplayRedis=locked.indexOf("await persistCheckpointMerged(paymentId",preReplayDurable)
const preReplayRelease=locked.indexOf("await releasePiWalletIntent",preReplayRedis)
must(preReplayAt>submitBranch&&movementAt>preReplayAt&&preReplayDurable>movementAt&&preReplayDurable<allowReplayAt,"already-moved replay must durably checkpoint Horizon before replay-submit eligibility")
must(preReplayRedis>preReplayDurable&&preReplayRelease>preReplayRedis,"already-moved ordering must be durable Horizon -> Redis projection -> wallet release")
must(locked.slice(movementAt,preReplayDurable).indexOf("await releasePiWalletIntent")<0,"wallet intent must not release before durable Horizon on already-moved replay")

const submitAt=locked.indexOf("await horizon.submitTransaction(transaction)",allowReplayAt)
const submitCatch=locked.indexOf('stage: "horizon_submit_exception"',submitAt)
const reconcileAt=locked.indexOf("await executeFinancialRecoverySettlementSubmitReplay({ payment: latestPayment, paymentId })",submitCatch)
const durableAt=locked.indexOf("await recordSettlementHorizonCheckpoint({",reconcileAt)
const redisAt=locked.indexOf("await persistCheckpointMerged(paymentId",durableAt)
const releaseAt=locked.indexOf("await releasePiWalletIntent",redisAt)
must(submitBranch>=0&&submitAt>submitBranch,"SETTLEMENT_SUBMIT production side effect missing")
must(submitCatch>submitAt&&reconcileAt>submitCatch,"ambiguous Horizon submit must reconcile exact evidence before decision")
must(!locked.slice(submitCatch,reconcileAt).includes('return { ok: false'),"submit exception must not return before exact Horizon reconciliation")
must(durableAt>reconcileAt&&redisAt>durableAt&&releaseAt>redisAt,"post-submit ordering must be exact proof -> durable Horizon -> Redis projection -> wallet release")
must(locked.slice(reconcileAt,durableAt).indexOf("await releasePiWalletIntent")<0,"wallet intent must not release before durable Horizon after submit")
must((locked.match(/await recordSettlementHorizonCheckpoint\(\{/g)||[]).length>=2,"both settlement recovery movement paths require durable Horizon checkpoint")
must(locked.includes('durableHorizon.outcome !== "RECORDED" && durableHorizon.outcome !== "REPLAYED"'),"durable Horizon fail-closed gate missing")

const refundSubmit=refund.indexOf("server.submitTransaction")
const refundCatch=refund.indexOf("catch",refundSubmit)
const refundReconcile=refund.indexOf("readRefundPreparedRecoveryEvidence",refundCatch)
must(refundSubmit>=0&&refundCatch>refundSubmit,"refund blockchain submit/catch boundary missing")
must(refundReconcile>refundCatch,"refund ambiguous submit must retain reconciliation path")

console.log("PLAN_H_CRASH_POLICY_BINDING=PASS modeled_windows=41 u2a_complete_reconcile=true settlement_submit_durable=true refund_ambiguity_bound=true blind_retry=false")
