import fs from "node:fs"; import path from "node:path"
const root=process.cwd(), route=fs.readFileSync(path.join(root,"app/api/certification/fin4-trigger/route.ts"),"utf8"), p=fs.readFileSync(path.join(root,"lib/fin4-r4n-stage1-ambiguity-probe.ts"),"utf8")
function must(c:boolean,l:string){if(!c)throw new Error(`FIN4_R4N_FAIL:${l}`)}
must(route.includes('evidence") === "r4n-stage1-ambiguity"'),"get_probe")
must(route.includes('fin4ArmedPaymentForRole(runId, "A")')&&route.includes('fin4ArmedPaymentForRole(runId, "B")'),"armed_exact_pair")
must(p.includes('WHERE payment_id IN ($1,$2)')&&p.includes('[paymentA, paymentB]'),"postgres_exact_pair")
must(p.includes('reconcileIncompleteA2UPayment(paymentA, amount, merchantUid)'),"pi_incomplete_read")
must(p.includes('pi.network === "Pi Testnet"')&&p.includes('pi.direction === "app_to_user"'),"network_direction")
must(p.includes('pi.amount === amount')&&p.includes('pi.user_uid === merchantUid'),"amount_uid")
must(p.includes('pi.from_address === sourceWallet'),"source_anchor")
must(p.includes('metadata?.type === "a2u_settlement"')&&p.includes('metadata?.paymentId === paymentA'),"metadata_exact")
must(p.includes('status?.cancelled === true')&&p.includes('status?.transaction_verified === true')&&p.includes('status?.developer_completed === true'),"progress_reject")
must(p.includes('/transactions?order=desc&limit=200&include_failed=true')&&p.includes('tx.memo === a2uPaymentId')&&p.includes('page < 20'),"horizon_absence")
must(p.includes('redis.get(`payment:${paymentA}`)'),"redis_read_only_projection")
must(p.includes('EXACT_UNMOVED_A2U_FOUND'),"explicit_safe_outcome")
for(const forbidden of ['method: "POST"','method:\'POST\'','redis.set','redis.del','redis.eval','query(`INSERT','query(`UPDATE','query(`DELETE','submitTransaction(','recordSettlement']) must(!p.includes(forbidden),`read_only_${forbidden}`)
must(p.includes('financialAuthorityMutated:false')&&p.includes('piMutationExecuted:false')&&p.includes('horizonSubmitExecuted:false')&&p.includes('redisMutated:false'),"mutation_flags")
console.log("FIN4_R4N_STAGE1_AMBIGUITY_PROBE=PASS exact_pair=true postgres_read=true redis_read=true pi_incomplete_read=true exact_identity=true horizon_absence=true fail_closed=true read_only=true")
