import fs from "node:fs"; import path from "node:path"
const root=process.cwd()
const route=fs.readFileSync(path.join(root,"app/api/certification/fin4-trigger/route.ts"),"utf8")
const locked=fs.readFileSync(path.join(root,"lib/a2u-locked-executor.ts"),"utf8")
const executor=fs.readFileSync(path.join(root,"lib/a2u-executor.ts"),"utf8")
function must(c:boolean,l:string){if(!c) throw new Error(`FIN4_R4M_FAIL:${l}`)}
const start=route.indexOf('if (body.action === "prepare-a-stage1")')
const end=route.indexOf('if (body.action === "prepare-b-stage1")',start)
must(start>=0&&end>start,"exact_a_action")
const a=route.slice(start,end)
must(route.includes('action: "launch" | "prepare-a-stage1" | "prepare-b-stage1"'),"body_contract")
must(a.includes('fin4ArmedPaymentForRole(runId, "A")'),"armed_a_binding")
must(a.includes('getDurableU2AIngressAuthoritative(paymentA)'),"durable_a_ingress")
must(a.includes('getSettlementCheckpointAuthoritative(paymentB)'),"durable_b_anchor")
must(a.includes('ingress.checkpoint.paymentId !== paymentA'),"exact_a_identity")
must(a.includes('anchor.checkpoint.paymentId !== paymentB'),"exact_b_anchor_identity")
must(a.includes('executeA2ULocked({ paymentId: paymentA, isRecovery: true, recoveryOperation: "FIN4_STAGE1_PREPARE" })'),"a_only_execution")
must(!a.includes('executeA2ULocked({ paymentId: paymentB'),"never_exec_b")
must(a.includes('targetAfter.checkpoint.paymentId === paymentA'),"post_exact_a")
must(a.includes('targetAfter.checkpoint.stage === "a2u_created"'),"durable_stage1")
must(a.includes('targetAfter.checkpoint.a2uFromAddress === anchor.checkpoint.a2uFromAddress'),"same_wallet")
must(a.includes('!targetAfter.checkpoint.a2uTxid'),"no_movement")
must(a.includes('horizonSubmitExecuted: false'),"response_no_horizon")
const certGate=locked.indexOf('params.recoveryOperation === "FIN4_STAGE1_PREPARE"'), dispatch=locked.indexOf('params.recoveryOperation === "SETTLEMENT_DISPATCH"')
must(certGate>=0&&dispatch>certGate&&locked.slice(certGate,dispatch).includes('isSettlementDispatchCandidate(latestPayment, now)'),"fresh_dispatch_contract")
must(!locked.slice(certGate,dispatch).includes('isStage1OnlySettlementDispatchCandidate'),"no_retry_widening")
const stop=executor.indexOf('ctx.recoveryOperation === "FIN4_STAGE1_PREPARE"'), stage2=executor.indexOf('// STAGE 2: Sign')
must(stop>=0&&stage2>stop&&executor.slice(stop,stage2).includes('return { ok: true, status: "settlement_pending" }'),"hard_stop_before_stage2")
console.log("FIN4_R4M_A_STAGE1_PREPARATION_GATE=PASS exact_a=true exact_b_anchor=true fresh_dispatch_contract=true cert_only_operation=true durable_a2u_created=true same_wallet=true no_a2u_txid=true hard_stop_before_stage2=true")
