import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert'
const root=join(__dirname,'..')
const db=readFileSync(join(root,'lib/db.ts'),'utf8')
const route=readFileSync(join(root,'app/api/pi/recover-pretransaction/route.ts'),'utf8')
const sdk=readFileSync(join(root,'lib/pi-sdk.ts'),'utf8')
const ops=readFileSync(join(root,'lib/operations.ts'),'utf8')
assert(route.includes("https://api.minepi.com/v2/me"))
assert(route.includes("before.pi.user_uid!==uid"))
assert(route.includes("pi.network==='Pi Testnet'"))
assert(route.includes("pi.direction==='user_to_app'"))
assert(route.includes("pi.amount===amount"))
assert(route.includes("pi.status?.transaction_verified===false"))
assert(route.includes("pi.status?.developer_completed===false"))
assert(route.includes("pi.transaction==null"))
assert(route.includes("https://api.testnet.minepi.com/accounts/"))
assert(route.includes("tx?.memo===piPaymentId"))
assert(route.includes("const horizonBefore=await proveHorizonAbsence"))
assert(route.includes("const horizonAfter=await proveHorizonAbsence"))
assert(route.includes("/cancel"))
assert(route.indexOf("const after=await getPi") > route.indexOf("/cancel"))
assert(route.indexOf("retireSettlementU2AApprovalAfterCanonicalCancellation") < route.lastIndexOf("retireSettlementU2AApprovalAfterCanonicalCancellation"))
assert(route.lastIndexOf("retireSettlementU2AApprovalAfterCanonicalCancellation") > route.indexOf("const after=await getPi"))
assert(db.includes("settlement_u2a_approval_retirements"))
assert(db.includes("PRIMARY KEY(payment_id, pi_payment_id)"))
assert(db.includes("pg_advisory_xact_lock(hashtextextended(${params.paymentId}, 0))"))
assert(db.includes("u2a_approval_identifier=${params.piPaymentId}"))
assert(db.includes("u2a_approval_identifier=NULL"))
assert(db.includes("u2a_identifier IS NULL AND u2a_txid IS NULL"))
assert(db.includes("a2u_payment_id IS NULL AND prepared_tx_hash IS NULL AND a2u_txid IS NULL AND horizon_confirmed_at IS NULL"))
assert(sdk.includes("onError: async (error: Error, piPayment?: any)"))
assert(sdk.includes("metadataPaymentId === paymentId"))
assert(sdk.includes("/api/pi/recover-pretransaction"))
assert(sdk.includes("onCancel: async (piPaymentId: string)"))
assert(ops.includes("recoveryAccessToken?: string"))
console.log('R4J_U2A_PRETRANSACTION_RECOVERY=PASS auth=true canonical_exact=true horizon_absence_pre_post=true cancel_reconciled=true append_only_retirement=true pg_advisory_lock=true progressed_state_blocked=true onerror_paymentdto=true oncancel_retirement=true')
