import fs from "node:fs"
import path from "node:path"
const root=process.cwd()
const route=fs.readFileSync(path.join(root,"app/api/certification/fin4-trigger/route.ts"),"utf8")
const q=fs.readFileSync(path.join(root,"lib/fin4-candidate-qualification.ts"),"utf8")
const scan=fs.readFileSync(path.join(root,"lib/fin4-submit-candidate-reader.ts"),"utf8")
function must(c:boolean,l:string){if(!c)throw new Error(`FIN4_R4L_FAIL:${l}`)}
must(route.includes('evidence") === "qualified-candidates"'),"get_only_probe")
must(route.includes('readFin4QualifiedExistingCandidates'),"route_reader")
must(q.includes('readFin4SameWalletSubmitCandidates(sourceWallet)'),"durable_shortlist")
must(q.includes('https://api.minepi.com/v2/payments/${encodeURIComponent(candidate.a2uPaymentId)}'),"exact_pi_get")
must(q.includes('pi.identifier !== candidate.a2uPaymentId'),"pi_identifier")
must(q.includes('pi.network !== "Pi Testnet" || pi.direction !== "app_to_user"'),"network_direction")
must(q.includes('pi.amount !== candidate.customerAmount || pi.user_uid !== candidate.merchantUid'),"amount_uid")
must(q.includes('pi.from_address !== sourceWallet'),"source_wallet")
must(q.includes('pi.metadata.type !== "a2u_settlement" || pi.metadata.paymentId !== candidate.paymentId'),"metadata")
must(q.includes('pi.status.cancelled === true || pi.status.user_cancelled === true'),"cancelled_rejected")
must(q.includes('pi.status.transaction_verified === true || pi.status.developer_completed === true'),"progress_rejected")
must(q.includes('pi.transaction != null'),"transaction_rejected")
must(q.includes('/transactions?order=desc&limit=200&include_failed=true'),"horizon_scan")
must(q.includes('tx.memo === a2uPaymentId'),"horizon_exact_memo")
must(q.includes('page < 20'),"bounded_scan")
must(q.includes('NO_SAFE_EXISTING_CANDIDATE'),"explicit_none")
for(const forbidden of ['method: "POST"','method:\'POST\'','submitTransaction(','redis.set','redis.del','query(`INSERT','query(`UPDATE','query(`DELETE']) must(!q.includes(forbidden),`read_only_${forbidden}`)
must(scan.includes('a2uPaymentId: string | null')&&scan.includes('merchantUid: string | null')&&scan.includes('customerAmount: number | null'),"durable_identity_fields")
console.log("FIN4_R4L_QUALIFIED_CANDIDATE_PROBE=PASS postgres_shortlist=true exact_pi_get=true cancelled_rejected=true progressed_rejected=true horizon_absence=true bounded=true fail_closed=true read_only=true")
